/* Preserve list navigation preferences in memory; never retain form fields. */
(function () {
  'use strict';
  var fields={'page.Page1':['pesquisanome','paginaatual'],'page.Page2':['pesquisanome','pesquisaInput'],'page.Page18':['filtrolead'],'page.Page19':['filtronegocio'],'page.Page21':['filtropagamento'],'page.Page22':['filtroacoes'],'page.Page24':['pesquisanome','paginaatual'],'page.Page27':['filtronegocio'],'page.Page28':[]};
  var saved={},adapters={},active=null,router,installed,generation=0,restored=-1,restoring=false,transition=false,recentCapture=0,scrollTimer;
  function page(){var m=location.pathname.match(/(?:m-)?page\.Page(\d+)/);return m?'page.Page'+m[1]:null;}
  function key(){return location.pathname+location.search;}
  function selector(el){if(el===document.scrollingElement)return '';var parts=[];while(el&&el!==document.documentElement){var parent=el.parentElement;if(!parent)return null;parts.unshift(el.tagName.toLowerCase()+':nth-child('+(Array.prototype.indexOf.call(parent.children,el)+1)+')');el=parent;}return 'html>'+parts.join('>');}
  function capture(){if(!active||restoring)return;var state={values:{},scroll:[]},adapter=adapters[active.page];(fields[active.page]||[]).forEach(function(k){if(adapter){var v=adapter.get(k);if(v!==undefined)state.values[k]=v;}});if(active.page==='page.Page1'||active.page==='page.Page24'||active.page==='page.Page2'){var search=document.querySelector('input[placeholder="Nome, telefone ou email"]');if(search){state.values.pesquisanome=search.value;if(active.page==='page.Page2')state.values.pesquisaInput=search.value;}}var root=document.scrollingElement;if(root)state.scroll.push({selector:'',x:root.scrollLeft,y:root.scrollTop});Array.prototype.forEach.call(document.querySelectorAll('*'),function(el){if(el.scrollHeight>el.clientHeight+1&&el.clientHeight>0&&el.scrollTop>0){var sel=selector(el);if(sel)state.scroll.push({selector:sel,x:el.scrollLeft,y:el.scrollTop});}});saved[active.key]=state;}
  function stop(){restoring=false;clearTimeout(scrollTimer);}
  function restoreScroll(state,token){var attempts=0;restoring=true;function apply(){if(token!==generation||!restoring)return;var ready=true;state.scroll.forEach(function(pos){var el=pos.selector?document.querySelector(pos.selector):document.scrollingElement;if(!el){ready=false;return;}el.scrollLeft=pos.x;el.scrollTop=pos.y;if(Math.abs(el.scrollTop-pos.y)>2)ready=false;});attempts++;if(attempts<400&&(!ready||attempts<40))scrollTimer=setTimeout(apply,25);else restoring=false;}apply();}
  function restore(){if(!active||restored===generation)return;var state=saved[active.key],adapter=adapters[active.page],token=generation;if(!state)return;if(fields[active.page].length&&!adapter)return;restored=token;restoring=true;setTimeout(function(){if(token!==generation)return;Object.keys(state.values).forEach(function(k){if(fields[active.page].indexOf(k)>=0)adapter.set(k,state.values[k]);});restoreScroll(state,token);},0);}
  function activate(){transition=false;generation++;restored=-1;stop();var p=page();active=Object.prototype.hasOwnProperty.call(fields,p)?{page:p,key:key()}:null;restore();}
  function install(){var r=router&&router.router;if(!r||installed===r)return;installed=r;if(r.events&&r.events.on){r.events.on('routeChangeStart',function(){if(Date.now()-recentCapture>1000)capture();stop();active=null;transition=true;});r.events.on('routeChangeComplete',activate);r.events.on('routeChangeError',activate);}}
  window.vfListMemory={router:function(r){router=r;install();},observe:function(context,adapter){install();if(!context||context.pageId!==page()||!Object.prototype.hasOwnProperty.call(fields,context.pageId))return;var previous=adapters[context.pageId];adapter.contextId=context.pageContextId;adapters[context.pageId]=adapter;if(previous&&previous.contextId!==adapter.contextId)restored=-1;if(transition)return;if(!active)active={page:context.pageId,key:key()};restore();}};
  document.addEventListener('pointerdown',function(){stop();capture();recentCapture=Date.now();},true);
  ['wheel','touchstart','keydown'].forEach(function(type){document.addEventListener(type,function(){if(restoring)stop();},true);});
  activate();
})();
